[project]
name = 'welsh-street-dex'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.comptroller]
path = 'contracts/comptroller.clar'
clarity_version = 4
epoch = 'latest'

[contracts.credit]
path = 'contracts/credit.clar'
clarity_version = 4
epoch = 'latest'

[contracts.exchange]
path = 'contracts/exchange.clar'
clarity_version = 4
epoch = 'latest'

[contracts.genesis]
path = 'contracts/genesis.clar'
clarity_version = 4
epoch = 'latest'

[contracts.rewards]
path = 'contracts/rewards.clar'
clarity_version = 4
epoch = 'latest'

[contracts.street]
path = 'contracts/street.clar'
clarity_version = 4
epoch = 'latest'

[contracts.welshcorgicoin]
path = 'contracts/welshcorgicoin.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
